/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Shapes2D.Transform;
import Object.Truck;
import Object.Windmill;
import Shapes2D.Circle;
import Shapes2D.Ellipse;
import Shapes2D.Line;
import Shapes2D.Pencil;
import Shapes2D.Rectangle;
import Shapes2D.Shape2D;
import Shapes2D.Triangle;
import Shapes3D.HinhCau;
import Shapes3D.HinhHop;
import Shapes3D.HinhNon;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.io.File;
import java.util.ArrayList;
import java.util.Stack;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Lương Vĩ Phú
 */
public class Display extends javax.swing.JFrame {
    
    /**
     * Creates new form TEST
     */
    
    private Point moveStart;
    private Point start, end;
    private String mode = "Pencil";
    private ArrayList<Shape2D> paint2D = new ArrayList<>();
    private Stack<Shape2D> stack = new Stack<>();
    private int size=5; // cỡ nét vẽ
    private Color color = Color.BLACK;// set màu cơ bản
    

    // Init Shape2D
    private Line line;
    private Rectangle rect;
    private Pencil pen;
    private Triangle triangle;
    private Circle circle;
    private Ellipse elip;
    private Windmill wm;
    private Truck t;
    
    public Display() {
        initComponents();
        panel3D.setVisible(false);
        rb2D.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public int ConvertX(int coor){
        return coor * size + panelDrawingArea.getWidth()/2;
    }
    
    public int ConvertY(int coor){
        return (-coor) * size + panelDrawingArea.getHeight()/2;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        if(cbGrid.isSelected()){
            new Coordinate().drawGrid(panelDrawingArea, panelDrawingArea.getGraphics());
        }
        if(cbCoordinate.isSelected() && rb2D.isSelected()){
            new Coordinate().drawCoor(panelDrawingArea, panelDrawingArea.getGraphics());
        }else if(cbCoordinate.isSelected() && rb3D.isSelected()){
            new Coordinate3D().drawCoor(panelDrawingArea, panelDrawingArea.getGraphics());
        }
        
        // Vẽ hình 2d
        if(rangBuoc2D() == true){
            if(butLine.isSelected()){
                line = new Line();
                line.init(start, end, size, color);
                line.draw(panelDrawingArea.getGraphics());
                paint2D.add(line);
            }else if(butRectangle.isSelected()){
                rect = new Rectangle();
                rect.init(start, end, size, color);
                rect.draw(panelDrawingArea.getGraphics());
                paint2D.add(rect);
            }else if(butCircle.isSelected()){
                circle = new Circle();
                circle.init(start, end, size, color);
                circle.draw(panelDrawingArea.getGraphics());
                paint2D.add(circle);
            }else if(butTriangle.isSelected()){
                triangle = new Triangle();
                triangle.init(end, start, size, color);
                triangle.draw(panelDrawingArea.getGraphics());
                paint2D.add(triangle);                
            }else if(butEllipse.isSelected()){
                elip = new Ellipse();
                elip.init(start, end, size, color);
                elip.draw(panelDrawingArea.getGraphics());
                paint2D.add(elip);                
            }
        }
        
        if(start != null && end !=null){
            if (cbSym.getSelectedItem().toString().equals("TRANSLATION")) {
                t.draw(panelDrawingArea.getGraphics());
            } else if (cbSym.getSelectedItem().toString().equals("SCALE")) {
                t.drawScale(panelDrawingArea.getGraphics(), (float) 0.5, (float) 0.5);
            }else if(cbSym.getSelectedItem().toString().equals("ROTATE")){
                wm.drawRotate(panelDrawingArea.getGraphics(), 45);
            }
        }
        else if(cbSym.getSelectedItem().toString().equals("ROTATE")){
                wm.drawRotate(panelDrawingArea.getGraphics(), 45);
            }
        
        // Vẽ hình 3d
        Graphics2D g2d = (Graphics2D) panelDrawingArea.getGraphics();
        if (rangBuoc3D() == true) {
            if (butCube.isSelected()) {
                HinhHop hh = new HinhHop();
                hh.setX(Integer.parseInt(tf3D_X.getText()));
                hh.setY(Integer.parseInt(tf3D_y.getText()));
                hh.setZ(Integer.parseInt(tf3D_Z.getText()));
                hh.setDai(Integer.parseInt(tf3D_Dai.getText()));
                hh.setRong(Integer.parseInt(tf3D_Rong.getText()));
                hh.setCao(Integer.parseInt(tf3D_Cao.getText()));
                hh.draw(g2d);
            } else if (butSphere.isSelected()) {
                HinhCau hc = new HinhCau();
                hc.setX(Integer.parseInt(tf3D_X.getText()));
                hc.setY(Integer.parseInt(tf3D_y.getText()));
                hc.setZ(Integer.parseInt(tf3D_Z.getText()));
                hc.setR(Integer.parseInt(tf3D_Dai.getText()));
                hc.draw(g2d);
            } else if (butCone.isSelected()) {
                HinhNon hn = new HinhNon();
                hn.setX(Integer.parseInt(tf3D_X.getText()));
                hn.setY(Integer.parseInt(tf3D_y.getText()));
                hn.setZ(Integer.parseInt(tf3D_Z.getText()));
                hn.setR(Integer.parseInt(tf3D_Dai.getText()));
                hn.setCao(Integer.parseInt(tf3D_Cao.getText()));
                hn.draw(g2d);
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_ = new javax.swing.ButtonGroup();
        bg2D = new javax.swing.ButtonGroup();
        bg3D = new javax.swing.ButtonGroup();
        panelDrawing = new javax.swing.JPanel();
        panelDrawingArea = new javax.swing.JPanel();
        panelSetUp = new javax.swing.JPanel();
        panel2D = new javax.swing.JPanel();
        panel2DStart = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf2D_SX = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf2D_SY = new javax.swing.JTextField();
        panel2DEnd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf2D_EX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf2D_EY = new javax.swing.JTextField();
        panel2DShape = new javax.swing.JPanel();
        butLine = new javax.swing.JToggleButton();
        butRectangle = new javax.swing.JToggleButton();
        butTriangle = new javax.swing.JToggleButton();
        butRhomb = new javax.swing.JToggleButton();
        butCircle = new javax.swing.JToggleButton();
        butEllipse = new javax.swing.JToggleButton();
        but = new javax.swing.JToggleButton();
        but2DPaint = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        panel3D = new javax.swing.JPanel();
        panel3DInput = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf3D_Dai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf3D_y = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf3D_Cao = new javax.swing.JTextField();
        tf3D_Rong = new javax.swing.JTextField();
        tf3D_Z = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf3D_X = new javax.swing.JTextField();
        panel3DShape = new javax.swing.JPanel();
        butSphere = new javax.swing.JToggleButton();
        butCube = new javax.swing.JToggleButton();
        butCone = new javax.swing.JToggleButton();
        but3DPaint = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        panelOperation = new javax.swing.JPanel();
        butOpenFile = new javax.swing.JButton();
        butSave = new javax.swing.JButton();
        butSetup = new javax.swing.JButton();
        panelHead = new javax.swing.JPanel();
        panelTool = new javax.swing.JPanel();
        butSelect = new javax.swing.JButton();
        butMove = new javax.swing.JButton();
        butUndo = new javax.swing.JButton();
        butPaint = new javax.swing.JButton();
        butErase = new javax.swing.JButton();
        butColour = new javax.swing.JButton();
        cbCustomLine = new javax.swing.JComboBox<>();
        cbSym = new javax.swing.JComboBox<>();
        rb2D = new javax.swing.JRadioButton();
        rb3D = new javax.swing.JRadioButton();
        butRedo = new javax.swing.JButton();
        butClean = new javax.swing.JButton();
        cbCoordinate = new javax.swing.JCheckBox();
        cbGrid = new javax.swing.JCheckBox();
        cbAxis = new javax.swing.JCheckBox();
        butDraw1 = new javax.swing.JButton();
        panelObject = new javax.swing.JPanel();
        butA1 = new javax.swing.JButton();
        butA2 = new javax.swing.JButton();
        panelAnimation = new javax.swing.JPanel();
        butA3 = new javax.swing.JButton();
        butA4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelDrawing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDrawingMouseClicked(evt);
            }
        });

        panelDrawingArea.setBackground(new java.awt.Color(255, 255, 255));
        panelDrawingArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDrawingArea.setPreferredSize(new java.awt.Dimension(990, 500));
        panelDrawingArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDrawingAreaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelDrawingAreaLayout = new javax.swing.GroupLayout(panelDrawingArea);
        panelDrawingArea.setLayout(panelDrawingAreaLayout);
        panelDrawingAreaLayout.setHorizontalGroup(
            panelDrawingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 988, Short.MAX_VALUE)
        );
        panelDrawingAreaLayout.setVerticalGroup(
            panelDrawingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        panelSetUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2D.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "2D", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        panel2DStart.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Start", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        jLabel4.setText("X:");

        jLabel5.setText("Y:");

        javax.swing.GroupLayout panel2DStartLayout = new javax.swing.GroupLayout(panel2DStart);
        panel2DStart.setLayout(panel2DStartLayout);
        panel2DStartLayout.setHorizontalGroup(
            panel2DStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DStartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf2D_SX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf2D_SY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel2DStartLayout.setVerticalGroup(
            panel2DStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DStartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2DStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf2D_SX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf2D_SY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel2DEnd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "End", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        jLabel2.setText("X:");

        jLabel3.setText("Y:");

        javax.swing.GroupLayout panel2DEndLayout = new javax.swing.GroupLayout(panel2DEnd);
        panel2DEnd.setLayout(panel2DEndLayout);
        panel2DEndLayout.setHorizontalGroup(
            panel2DEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DEndLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf2D_EX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf2D_EY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel2DEndLayout.setVerticalGroup(
            panel2DEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DEndLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2DEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf2D_EX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tf2D_EY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel2DShape.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Shape", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        bg2D.add(butLine);
        butLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Line.png"))); // NOI18N

        bg2D.add(butRectangle);
        butRectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rectangle.png"))); // NOI18N

        bg2D.add(butTriangle);
        butTriangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/triangle.png"))); // NOI18N

        bg2D.add(butRhomb);
        butRhomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rhomb-outline.png"))); // NOI18N

        bg2D.add(butCircle);
        butCircle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/circle.png"))); // NOI18N

        bg2D.add(butEllipse);
        butEllipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ellipse.png"))); // NOI18N

        bg2D.add(but);
        but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/trapeze.png"))); // NOI18N

        javax.swing.GroupLayout panel2DShapeLayout = new javax.swing.GroupLayout(panel2DShape);
        panel2DShape.setLayout(panel2DShapeLayout);
        panel2DShapeLayout.setHorizontalGroup(
            panel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DShapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2DShapeLayout.createSequentialGroup()
                        .addComponent(butLine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2DShapeLayout.createSequentialGroup()
                        .addGroup(panel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2DShapeLayout.createSequentialGroup()
                                .addComponent(butTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butRhomb, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(but, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel2DShapeLayout.setVerticalGroup(
            panel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DShapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butLine, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butRhomb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        but2DPaint.setText("Paint");
        but2DPaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2DPaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2DLayout = new javax.swing.GroupLayout(panel2D);
        panel2D.setLayout(panel2DLayout);
        panel2DLayout.setHorizontalGroup(
            panel2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panel2DShape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel2DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(but2DPaint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panel2DEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel2DStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel2DLayout.setVerticalGroup(
            panel2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2DStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2DEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2DShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but2DPaint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSetUp.add(panel2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        panel3D.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "3D", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        panel3DInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        jLabel6.setText("X:");

        jLabel1.setText("Z:");

        jLabel12.setText("Rộng:");

        jLabel7.setText("Y:");

        jLabel13.setText("Cao:");

        jLabel11.setText("Dài/R:");

        javax.swing.GroupLayout panel3DInputLayout = new javax.swing.GroupLayout(panel3DInput);
        panel3DInput.setLayout(panel3DInputLayout);
        panel3DInputLayout.setHorizontalGroup(
            panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3DInputLayout.createSequentialGroup()
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf3D_X)
                    .addComponent(tf3D_Z)
                    .addComponent(tf3D_Rong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf3D_y)
                    .addComponent(tf3D_Dai)
                    .addComponent(tf3D_Cao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3DInputLayout.setVerticalGroup(
            panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf3D_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tf3D_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf3D_Z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tf3D_Dai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf3D_Rong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf3D_Cao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panel3DShape.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Shape", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        bg3D.add(butSphere);
        butSphere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sphere.png"))); // NOI18N

        bg3D.add(butCube);
        butCube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cuboid.png"))); // NOI18N

        bg3D.add(butCone);
        butCone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cone.png"))); // NOI18N

        javax.swing.GroupLayout panel3DShapeLayout = new javax.swing.GroupLayout(panel3DShape);
        panel3DShape.setLayout(panel3DShapeLayout);
        panel3DShapeLayout.setHorizontalGroup(
            panel3DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DShapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butCube, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butCone, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butSphere, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3DShapeLayout.setVerticalGroup(
            panel3DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DShapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butCone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel3DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(butSphere, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butCube, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        but3DPaint.setText("Paint");
        but3DPaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3DPaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3DLayout = new javax.swing.GroupLayout(panel3D);
        panel3D.setLayout(panel3DLayout);
        panel3DLayout.setHorizontalGroup(
            panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3DLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(but3DPaint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(panel3DShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panel3DInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel3DLayout.setVerticalGroup(
            panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel3DInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3DShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(but3DPaint)
                .addGap(19, 19, 19))
        );

        panelSetUp.add(panel3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        javax.swing.GroupLayout panelDrawingLayout = new javax.swing.GroupLayout(panelDrawing);
        panelDrawing.setLayout(panelDrawingLayout);
        panelDrawingLayout.setHorizontalGroup(
            panelDrawingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDrawingLayout.createSequentialGroup()
                .addComponent(panelSetUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDrawingArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDrawingLayout.setVerticalGroup(
            panelDrawingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDrawingLayout.createSequentialGroup()
                .addGroup(panelDrawingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDrawingArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSetUp, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelOperation.setBackground(new java.awt.Color(0, 0, 0));
        panelOperation.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        butOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Open File.png"))); // NOI18N
        butOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOpenFileActionPerformed(evt);
            }
        });

        butSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
        butSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSaveActionPerformed(evt);
            }
        });

        butSetup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Setup.png"))); // NOI18N

        javax.swing.GroupLayout panelOperationLayout = new javax.swing.GroupLayout(panelOperation);
        panelOperation.setLayout(panelOperationLayout);
        panelOperationLayout.setHorizontalGroup(
            panelOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperationLayout.createSequentialGroup()
                .addComponent(butOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOperationLayout.setVerticalGroup(
            panelOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(butSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(butOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(butSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelTool.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tools", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        butSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Move.png"))); // NOI18N

        butMove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/crop-tool.png"))); // NOI18N

        butUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/undo.png"))); // NOI18N

        butPaint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/paint-bucket.png"))); // NOI18N

        butErase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Eraser.png"))); // NOI18N

        butColour.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        butColour.setText("Color");
        butColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butColourActionPerformed(evt);
            }
        });

        cbCustomLine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEFAULT", "DASH", "DOT", "DASHDOT", "DASHDOTDOT", "ARROW" }));

        cbSym.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRANSLATION", "ROTATE", "SCALE", "SYMMYETRY" }));

        bg_.add(rb2D);
        rb2D.setText("2D");
        rb2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2DActionPerformed(evt);
            }
        });

        bg_.add(rb3D);
        rb3D.setText("3D");
        rb3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3DActionPerformed(evt);
            }
        });

        butRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/redo.png"))); // NOI18N

        butClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Clean.png"))); // NOI18N

        cbCoordinate.setText("Coordinate");
        cbCoordinate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbCoordinateStateChanged(evt);
            }
        });
        cbCoordinate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbCoordinateFocusLost(evt);
            }
        });
        cbCoordinate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCoordinateActionPerformed(evt);
            }
        });

        cbGrid.setText("Gridline");
        cbGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGridActionPerformed(evt);
            }
        });

        cbAxis.setText("Axis");

        butDraw1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Pencil.png"))); // NOI18N

        javax.swing.GroupLayout panelToolLayout = new javax.swing.GroupLayout(panelTool);
        panelTool.setLayout(panelToolLayout);
        panelToolLayout.setHorizontalGroup(
            panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelToolLayout.createSequentialGroup()
                        .addComponent(butMove, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butPaint, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butColour, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(cbSym, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelToolLayout.createSequentialGroup()
                        .addComponent(butUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butRedo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butClean, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butDraw1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butErase, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCustomLine, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbCoordinate)))
                .addGap(18, 18, 18)
                .addGroup(panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelToolLayout.createSequentialGroup()
                        .addComponent(rb2D)
                        .addGap(18, 18, 18)
                        .addComponent(rb3D))
                    .addComponent(cbAxis))
                .addGap(229, 229, 229))
        );
        panelToolLayout.setVerticalGroup(
            panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butRedo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butClean, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butDraw1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butErase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCustomLine, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbCoordinate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb2D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb3D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSym)
                    .addGroup(panelToolLayout.createSequentialGroup()
                        .addGroup(panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(butMove, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(butSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(butColour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butPaint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbAxis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelObject.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Object", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        butA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/car.png"))); // NOI18N
        butA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA1ActionPerformed(evt);
            }
        });

        butA2.setText("C");
        butA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelObjectLayout = new javax.swing.GroupLayout(panelObject);
        panelObject.setLayout(panelObjectLayout);
        panelObjectLayout.setHorizontalGroup(
            panelObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butA1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butA2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelObjectLayout.setVerticalGroup(
            panelObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butA2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butA1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAnimation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Animations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        butA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/car.png"))); // NOI18N

        javax.swing.GroupLayout panelAnimationLayout = new javax.swing.GroupLayout(panelAnimation);
        panelAnimation.setLayout(panelAnimationLayout);
        panelAnimationLayout.setHorizontalGroup(
            panelAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnimationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butA3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butA4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAnimationLayout.setVerticalGroup(
            panelAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnimationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butA4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butA3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelHeadLayout = new javax.swing.GroupLayout(panelHead);
        panelHead.setLayout(panelHeadLayout);
        panelHeadLayout.setHorizontalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeadLayout.createSequentialGroup()
                .addComponent(panelTool, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelObject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeadLayout.setVerticalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelObject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelAnimation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDrawing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDrawing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    boolean rangBuoc2D() {
        String x1 = tf2D_SX.getText();
        String y1 = tf2D_SY.getText();
        String x2 = tf2D_EX.getText();
        String y2 = tf2D_EY.getText();
        if (x1.equals("") || y1.equals("") || x2.equals("") || y2.equals("")) {
            return false;
        }
        return true;
    }
    
    boolean rangBuoc3D() {
        String x = tf3D_X.getText();
        String y = tf3D_y.getText();
        String z = tf3D_Z.getText();
        String dai = tf3D_Dai.getText();
        String rong = tf3D_Rong.getText();
        String cao = tf3D_Cao.getText();
        if (x.equals("") ||y.equals("") ||z.equals("") || dai.equals("") || rong.equals("") || cao.equals("")) {
            return false;
        }
        return true;
    }
    
    private void rb2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2DActionPerformed
        panel2D.setVisible(true);
        panel3D.setVisible(false);
        if(cbCoordinate.isSelected()){
            repaint();
        }
    }//GEN-LAST:event_rb2DActionPerformed

    private void rb3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3DActionPerformed
        panel2D.setVisible(false);
        panel3D.setVisible(true);
        if(cbCoordinate.isSelected()){
            repaint();
        }
    }//GEN-LAST:event_rb3DActionPerformed

    private void cbCoordinateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCoordinateActionPerformed
        // TODO add your handling code here:
        repaint();
    }//GEN-LAST:event_cbCoordinateActionPerformed

    private void cbCoordinateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbCoordinateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCoordinateFocusLost

    private void cbCoordinateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbCoordinateStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCoordinateStateChanged

    private void butColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butColourActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose Color ", Color.white);
        butColour.setBackground(color);
    }//GEN-LAST:event_butColourActionPerformed

    private void butOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOpenFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("image", "jpg", "png");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setMultiSelectionEnabled(false);

        int x = fileChooser.showDialog(this, "Chose file");
        if (x == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String pathFile = file.getAbsolutePath().replace("//", "--");
            try {

                paintComponent(panelDrawingArea.getGraphics(),new ImageIcon(pathFile));
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_butOpenFileActionPerformed

    public void paintComponent(Graphics g, ImageIcon icon) {
//        super.paintComponent(g);
        Dimension d = panelDrawingArea.getSize();
        g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
        setOpaque(false);
    }
 

    private void butSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSaveActionPerformed

    }//GEN-LAST:event_butSaveActionPerformed

    private void but2DPaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2DPaintActionPerformed
//        if(rangBuoc2D() == true){
//            start = new Point();
//            end = new Point();
//            start.x = ConvertX(Integer.parseInt(tf2D_SX.getText()));
//            start.y = ConvertY(Integer.parseInt(tf2D_SY.getText()));
//            end.x = ConvertX(Integer.parseInt(tf2D_EX.getText()));
//            end.y = ConvertY(Integer.parseInt(tf2D_EY.getText()));
//            repaint();
//        }
//        else{
//            JOptionPane.showMessageDialog(this,"Vui lòng điển đủ tọa độ" );
//        }
        
        if(cbSym.getSelectedItem().toString().equals("TRANSLATION")){
            Transform trans = new Transform();
            Point tr = trans.translation(t.getO(), 10, 0);
            System.out.println(tr);
            t.setO(new Point(tr.x, tr.y));
            t.init();
//            t.draw(panelDrawingArea.getGraphics());
            repaint();
        }else if(cbSym.getSelectedItem().toString().equals("ROTATE")){
            
            repaint();
        }else if(cbSym.getSelectedItem().toString().equals("SCALE")){
            repaint();
        }else if(cbSym.getSelectedItem().toString().equals("SYMMYETRY")){
//            t.setO(new Point(ConvertX(tr.x), ConvertY(tr.y)));
            t.drawSym(panelDrawingArea.getGraphics());
        }
    }//GEN-LAST:event_but2DPaintActionPerformed

    private void panelDrawingAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawingAreaMouseClicked

    }//GEN-LAST:event_panelDrawingAreaMouseClicked

    private void panelDrawingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawingMouseClicked
        System.out.println(evt.getX()  + ", " + evt.getY());
    }//GEN-LAST:event_panelDrawingMouseClicked

    private void cbGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGridActionPerformed
        // TODO add your handling code here:
        repaint();
    }//GEN-LAST:event_cbGridActionPerformed

    private void but3DPaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3DPaintActionPerformed
        
    }//GEN-LAST:event_but3DPaintActionPerformed

    private void butA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA2ActionPerformed
        // TODO add your handling code here:
        Point O = new Point(ConvertX(0), ConvertY(10));
        wm = new Windmill(O, size, 40, Color.blue);
        wm.init();
        wm.draw(panelDrawingArea.getGraphics());
    }//GEN-LAST:event_butA2ActionPerformed

    private void butA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA1ActionPerformed
        // TODO add your handling code here:
        Point O = new Point(ConvertX(0), ConvertY(10));
        t = new Truck(O, 70, 5);
        t.init();
        t.draw(panelDrawingArea.getGraphics());
    }//GEN-LAST:event_butA1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg2D;
    private javax.swing.ButtonGroup bg3D;
    private javax.swing.ButtonGroup bg_;
    private javax.swing.JToggleButton but;
    private javax.swing.JButton but2DPaint;
    private javax.swing.JButton but3DPaint;
    private javax.swing.JButton butA1;
    private javax.swing.JButton butA2;
    private javax.swing.JButton butA3;
    private javax.swing.JButton butA4;
    private javax.swing.JToggleButton butCircle;
    private javax.swing.JButton butClean;
    private javax.swing.JButton butColour;
    private javax.swing.JToggleButton butCone;
    private javax.swing.JToggleButton butCube;
    private javax.swing.JButton butDraw1;
    private javax.swing.JToggleButton butEllipse;
    private javax.swing.JButton butErase;
    private javax.swing.JToggleButton butLine;
    private javax.swing.JButton butMove;
    private javax.swing.JButton butOpenFile;
    private javax.swing.JButton butPaint;
    private javax.swing.JToggleButton butRectangle;
    private javax.swing.JButton butRedo;
    private javax.swing.JToggleButton butRhomb;
    private javax.swing.JButton butSave;
    private javax.swing.JButton butSelect;
    private javax.swing.JButton butSetup;
    private javax.swing.JToggleButton butSphere;
    private javax.swing.JToggleButton butTriangle;
    private javax.swing.JButton butUndo;
    private javax.swing.JCheckBox cbAxis;
    private javax.swing.JCheckBox cbCoordinate;
    private javax.swing.JComboBox<String> cbCustomLine;
    private javax.swing.JCheckBox cbGrid;
    private javax.swing.JComboBox<String> cbSym;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel panel2D;
    private javax.swing.JPanel panel2DEnd;
    private javax.swing.JPanel panel2DShape;
    private javax.swing.JPanel panel2DStart;
    private javax.swing.JPanel panel3D;
    private javax.swing.JPanel panel3DInput;
    private javax.swing.JPanel panel3DShape;
    private javax.swing.JPanel panelAnimation;
    private javax.swing.JPanel panelDrawing;
    private javax.swing.JPanel panelDrawingArea;
    private javax.swing.JPanel panelHead;
    private javax.swing.JPanel panelObject;
    private javax.swing.JPanel panelOperation;
    private javax.swing.JPanel panelSetUp;
    private javax.swing.JPanel panelTool;
    private javax.swing.JRadioButton rb2D;
    private javax.swing.JRadioButton rb3D;
    private javax.swing.JTextField tf2D_EX;
    private javax.swing.JTextField tf2D_EY;
    private javax.swing.JTextField tf2D_SX;
    private javax.swing.JTextField tf2D_SY;
    private javax.swing.JTextField tf3D_Cao;
    private javax.swing.JTextField tf3D_Dai;
    private javax.swing.JTextField tf3D_Rong;
    private javax.swing.JTextField tf3D_X;
    private javax.swing.JTextField tf3D_Z;
    private javax.swing.JTextField tf3D_y;
    // End of variables declaration//GEN-END:variables

    private void setOpaque(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
